"""CoScope Core Types and Interfaces."""

from coscope.core.types import (
    Agent,
    AgentConfig,
    AgentRole,
    AgentState,
    EdgeType,
    EmbeddingProvider,
    Episode,
    GoTEdge,
    GoTGraph,
    GoTNode,
    GraphType,
    GroundTruthEvidence,
    InvalidGraphError,
    MemoryEntry,
    MemoryStore,
    MemoryType,
    NodeType,
    PolicyConstraints,
    Provenance,
    QueryMatrix,
    ReasoningPathType,
    RetrievalRequest,
    RetrievalResult,
    RetrievedCandidate,
    ScopeBucketKey,
    ScopeSpec,
    ScopeType,
    SharedCandidatePool,
    SharedProjectionResult,
    SubsetLabel,
    VisibilityLevel,
)
from coscope.core.artifact_types import (
    ArtifactSlot,
    ArtifactTrace,
    MEMORY_TYPE_BY_SLOT,
    SCOPE_LAYER_BY_SLOT,
    VISIBILITY_BY_SLOT,
)
from coscope.core.scope_ids import (
    agent_private,
    LAYER_VISIBILITY,
    SCOPE_LAYERS,
    task_restricted,
    task_shared,
    workspace_semantic,
)
from coscope.core.interfaces import (
    AbstractDatasetPipeline,
    AbstractEpisodeBuilder,
    AbstractGraphBuilder,
    AbstractLoader,
    AbstractRolloutEngine,
    AbstractScopeBuilder,
    Embedder,
    EmbeddingResult,
    LLMClient,
    LLMResponse,
)

__all__ = [
    # runtime types
    "Agent",
    "AgentConfig",
    "AgentRole",
    "AgentState",
    "EmbeddingProvider",
    "MemoryEntry",
    "MemoryStore",
    "MemoryType",
    "PolicyConstraints",
    "Provenance",
    "QueryMatrix",
    "RetrievalRequest",
    "RetrievalResult",
    "RetrievedCandidate",
    "ScopeBucketKey",
    "ScopeSpec",
    "ScopeType",
    "SharedCandidatePool",
    "SharedProjectionResult",
    "VisibilityLevel",
    # graph / episode types
    "EdgeType",
    "Episode",
    "GoTEdge",
    "GoTGraph",
    "GoTNode",
    "GraphType",
    "GroundTruthEvidence",
    "InvalidGraphError",
    "NodeType",
    "ReasoningPathType",
    "SubsetLabel",
    # artifact types
    "ArtifactSlot",
    "ArtifactTrace",
    "MEMORY_TYPE_BY_SLOT",
    "SCOPE_LAYER_BY_SLOT",
    "VISIBILITY_BY_SLOT",
    # scope ids
    "agent_private",
    "LAYER_VISIBILITY",
    "SCOPE_LAYERS",
    "task_restricted",
    "task_shared",
    "workspace_semantic",
    # interfaces / protocols
    "AbstractDatasetPipeline",
    "AbstractEpisodeBuilder",
    "AbstractGraphBuilder",
    "AbstractLoader",
    "AbstractRolloutEngine",
    "AbstractScopeBuilder",
    "Embedder",
    "EmbeddingResult",
    "LLMClient",
    "LLMResponse",
]
