"""CoScope Core Types and Interfaces."""

from coscope.core.types import (
    Agent,
    AgentConfig,
    AgentRole,
    AgentState,
    EmbeddingProvider,
    MemoryEntry,
    MemoryStore,
    MemoryType,
    PolicyConstraints,
    Provenance,
    QueryMatrix,
    RetrievalRequest,
    RetrievalResult,
    RetrievedCandidate,
    ScopeBucketKey,
    ScopeSpec,
    ScopeType,
    SharedCandidatePool,
    SharedProjectionResult,
    VisibilityLevel,
)

__all__ = [
    "Agent",
    "AgentConfig",
    "AgentRole",
    "AgentState",
    "EmbeddingProvider",
    "MemoryEntry",
    "MemoryStore",
    "MemoryType",
    "PolicyConstraints",
    "Provenance",
    "QueryMatrix",
    "RetrievalRequest",
    "RetrievalResult",
    "RetrievedCandidate",
    "ScopeBucketKey",
    "ScopeSpec",
    "ScopeType",
    "SharedCandidatePool",
    "SharedProjectionResult",
    "VisibilityLevel",
]
